// Auto-generated by backend from production_plan.json
// Assumes loadAssets, createAnimations, createScene, setupControls, runCombatLoop are loaded globally.

class GameScene extends Phaser.Scene {
    constructor() {
        super({ key: 'GameScene' });
    }
    preload() {
        if (window.loadAssets) window.loadAssets(this);
    }
    create() {
        if (window.createAnimations) window.createAnimations(this);
        if (window.createScene) window.createScene(this);
        if (window.setupControls) window.setupControls(this);
        // runCombatLoop is called in update
    }
    update(time, delta) {
        if (window.runCombatLoop) window.runCombatLoop(this, delta);
    }
}
window.GameScene = GameScene;
